# Generated by Django 3.1.7 on 2025-01-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='approved',
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='dashboard.status'),
        ),
    ]
