# Generated by Django 3.1.7 on 2025-01-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20250128_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timezone_sensors', to='dashboard.timezonechoices'),
        ),
    ]
