# Generated by Django 3.1.7 on 2025-01-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sensor_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='dashboard.trip'),
        ),
    ]
