# Generated by Django 3.1.7 on 2025-01-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20250129_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='decision_messages',
        ),
        migrations.DeleteModel(
            name='DecisionMessage',
        ),
    ]
